# Dockerfile.backend.prod
FROM node:22-alpine

WORKDIR /app

# Только production-зависимости
COPY package*.json ./
RUN npm ci --omit=dev

# Копируем данные
COPY data/db.json ./data/db.json

# Безопасность
USER node

EXPOSE 3000

# Запуск без --watch!
CMD ["npx", "json-server", "data/db.json", "--port", "3000", "--host", "0.0.0.0"]
