version: '3.8'

services:
  vue-app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      json-server:
        condition: service_healthy  # ← ждём, пока healthcheck пройдёт

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    volumes:
      - ./data:/data
    # ports: ← УБРАНО! Теперь бэкенд НЕДОСТУПЕН снаружи
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
