name: Deploy Vue App to GitHub Pages

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏗️ Build application
        run: |
          # Создаём .env.production для GitHub Pages (статический хостинг → моки)
          echo "VITE_API_BASE_URL=/" > .env.production
          echo "VITE_APP_TITLE=Vue Composition API App" >> .env.production
          
          # Собираем приложение
          npm run build
          echo "✅ Приложение успешно собрано!"

      - name: 🔍 Verify build output
        run: |
          echo "=== PROJECT STRUCTURE ==="
          ls -la
          echo "=== DIST CONTENTS (HTML/JS/CSS) ==="
          find dist/ -type f \( -name "*.html" -o -name "*.js" -o -name "*.css" \) | head -20
          echo "=== ASSETS IN index.html ==="
          grep -oE '(src|href)="[^"]*"' dist/index.html || echo "⚠️ No assets found in index.html"

      - name: 📁 Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

      - name: 🚀 Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: ✅ Deployment info
        run: |
          echo "🎉 Приложение опубликовано!"
          echo "🔗 URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          echo "📝 Примечание: На GitHub Pages используются мок-данные (нет бэкенда)."
